[package]
name = "rs_rank_choices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
itertools = "0.10"
xlsxwriter = "0.3"
